on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  check:
    steps:
      - uses: ./.github/actions/check-for-go-ipfs-release
  verify:
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
  publish:
    needs: verify
    steps:
      - uses: ./.github/actions/publish
